version: "3.9"
services:
  razor-miniflux: # Should be exact same name as "id" field in config.json
    container_name: razor-miniflux # Should be exact same name as "id" field in config.json
    image: romesc/razorminiflux:1731810253 # Try to avoid "latest" tag. As it may break configs in the future.
    restart: unless-stopped # Do not change this
    environment:
      - TZ=${TZ} # Can use any env variable. See "environment variables" section in the docs
      - MINIFLUX_URL=${MINIFLUX_URL}
      - MINIFLUX_TOKEN=${MINIFLUX_TOKEN}
      - MINIFLUX_TOKEN_TOP=${MINIFLUX_TOKEN_TOP}
      - IPTV_URL=${IPTV_URL}
      - PAGE_SIZE=${PAGE_SIZE}
      - IS_TOP=${IS_TOP}
    volumes:
      - ${APP_DATA_DIR}/data/db:/app/db # Always start the path with ${APP_DATA_DIR}/data/. This will put all data inside app-data/my-app/data
    ports:
      - ${APP_PORT}:8080
    networks:
      - tipi_main_network # That should not be changed
    labels: # Use your editors search and replace feature to replace all instances of "razor-miniflux" with your app name in the traefik labels
      # Main
      traefik.enable: true
      traefik.http.middlewares.razor-miniflux-web-redirect.redirectscheme.scheme: https
      traefik.http.services.razor-miniflux.loadbalancer.server.port: 8080 # Should be the same as the app internal port so for this example 9443
      # Web
      traefik.http.routers.razor-miniflux-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.razor-miniflux-insecure.entrypoints: web
      traefik.http.routers.razor-miniflux-insecure.service: razor-miniflux
      traefik.http.routers.razor-miniflux-insecure.middlewares: razor-miniflux-web-redirect
      # Websecure
      traefik.http.routers.razor-miniflux.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.razor-miniflux.entrypoints: websecure
      traefik.http.routers.razor-miniflux.service: razor-miniflux
      traefik.http.routers.razor-miniflux.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.razor-miniflux-local-insecure.rule: Host(`razor-miniflux.${LOCAL_DOMAIN}`)
      traefik.http.routers.razor-miniflux-local-insecure.entrypoints: web
      traefik.http.routers.razor-miniflux-local-insecure.service: razor-miniflux
      traefik.http.routers.razor-miniflux-local-insecure.middlewares: razor-miniflux-web-redirect
      # Local domain secure
      traefik.http.routers.razor-miniflux-local.rule: Host(`razor-miniflux.${LOCAL_DOMAIN}`)
      traefik.http.routers.razor-miniflux-local.entrypoints: websecure
      traefik.http.routers.razor-miniflux-local.service: razor-miniflux
      traefik.http.routers.razor-miniflux-local.tls: true
