version: "3.9"
services:
  razor-pricehistory: # Should be exact same name as "id" field in config.json
    container_name: razor-pricehistory # Should be exact same name as "id" field in config.json
    image: romesc/razorpricehistory:1733756296 # Try to avoid "latest" tag. As it may break configs in the future.
    restart: unless-stopped # Do not change this
    environment:
      - TZ=${TZ} # Can use any env variable. See "environment variables" section in the docs
    volumes:
      - ${APP_DATA_DIR}/data/db:/app/db # Always start the path with ${APP_DATA_DIR}/data/. This will put all data inside app-data/my-app/data
    ports:
      - ${APP_PORT}:8080
    networks:
      - tipi_main_network # That should not be changed
    labels: # Use your editors search and replace feature to replace all instances of "razor-pricehistory" with your app name in the traefik labels
      # Main
      traefik.enable: true
      traefik.http.middlewares.razor-pricehistory-web-redirect.redirectscheme.scheme: https
      traefik.http.services.razor-pricehistory.loadbalancer.server.port: 8080 # Should be the same as the app internal port so for this example 9443
      # Web
      traefik.http.routers.razor-pricehistory-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.razor-pricehistory-insecure.entrypoints: web
      traefik.http.routers.razor-pricehistory-insecure.service: razor-pricehistory
      traefik.http.routers.razor-pricehistory-insecure.middlewares: razor-pricehistory-web-redirect
      # Websecure
      traefik.http.routers.razor-pricehistory.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.razor-pricehistory.entrypoints: websecure
      traefik.http.routers.razor-pricehistory.service: razor-pricehistory
      traefik.http.routers.razor-pricehistory.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.razor-pricehistory-local-insecure.rule: Host(`razor-pricehistory.${LOCAL_DOMAIN}`)
      traefik.http.routers.razor-pricehistory-local-insecure.entrypoints: web
      traefik.http.routers.razor-pricehistory-local-insecure.service: razor-pricehistory
      traefik.http.routers.razor-pricehistory-local-insecure.middlewares: razor-pricehistory-web-redirect
      # Local domain secure
      traefik.http.routers.razor-pricehistory-local.rule: Host(`razor-pricehistory.${LOCAL_DOMAIN}`)
      traefik.http.routers.razor-pricehistory-local.entrypoints: websecure
      traefik.http.routers.razor-pricehistory-local.service: razor-pricehistory
      traefik.http.routers.razor-pricehistory-local.tls: true
      runtipi.managed: true
